package org.app.appgenesis.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table COMENTARIO.
 */
public class Comentario {

    private Long id;
    private String comecons;
    private String comedesc;
    private String comedano;
    private String comeorde;
    private String comesoli;
    private String comequej;
    private String comerevi;
    private String comeuscr;
    private String comefecr;
    private String comeesta;
    private Long idOrden;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Comentario() {
    }

    public Comentario(Long id) {
        this.id = id;
    }

    public Comentario(Long id, String comecons, String comedesc, String comedano, String comeorde, String comesoli, String comequej, String comerevi, String comeuscr, String comefecr, String comeesta, Long idOrden) {
        this.id = id;
        this.comecons = comecons;
        this.comedesc = comedesc;
        this.comedano = comedano;
        this.comeorde = comeorde;
        this.comesoli = comesoli;
        this.comequej = comequej;
        this.comerevi = comerevi;
        this.comeuscr = comeuscr;
        this.comefecr = comefecr;
        this.comeesta = comeesta;
        this.idOrden = idOrden;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getComecons() {
        return comecons;
    }

    public void setComecons(String comecons) {
        this.comecons = comecons;
    }

    public String getComedesc() {
        return comedesc;
    }

    public void setComedesc(String comedesc) {
        this.comedesc = comedesc;
    }

    public String getComedano() {
        return comedano;
    }

    public void setComedano(String comedano) {
        this.comedano = comedano;
    }

    public String getComeorde() {
        return comeorde;
    }

    public void setComeorde(String comeorde) {
        this.comeorde = comeorde;
    }

    public String getComesoli() {
        return comesoli;
    }

    public void setComesoli(String comesoli) {
        this.comesoli = comesoli;
    }

    public String getComequej() {
        return comequej;
    }

    public void setComequej(String comequej) {
        this.comequej = comequej;
    }

    public String getComerevi() {
        return comerevi;
    }

    public void setComerevi(String comerevi) {
        this.comerevi = comerevi;
    }

    public String getComeuscr() {
        return comeuscr;
    }

    public void setComeuscr(String comeuscr) {
        this.comeuscr = comeuscr;
    }

    public String getComefecr() {
        return comefecr;
    }

    public void setComefecr(String comefecr) {
        this.comefecr = comefecr;
    }

    public String getComeesta() {
        return comeesta;
    }

    public void setComeesta(String comeesta) {
        this.comeesta = comeesta;
    }

    public Long getIdOrden() {
        return idOrden;
    }

    public void setIdOrden(Long idOrden) {
        this.idOrden = idOrden;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
