package org.app.appgenesis.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import org.app.appgenesis.dao.Persona;
import org.app.appgenesis.dao.OrdePers;
import org.app.appgenesis.dao.Material;
import org.app.appgenesis.dao.OrdeMate;
import org.app.appgenesis.dao.Dibujo;
import org.app.appgenesis.dao.Firma;
import org.app.appgenesis.dao.Comentario;
import org.app.appgenesis.dao.Fotografia;
import org.app.appgenesis.dao.Gop_ordeatri;
import org.app.appgenesis.dao.GOP_ATRIBUTOS;
import org.app.appgenesis.dao.GOP_ORDEESTA;
import org.app.appgenesis.dao.Gma_costtitr;
import org.app.appgenesis.dao.Gro_orden;
import org.app.appgenesis.dao.UnidadMedida;
import org.app.appgenesis.dao.GMA_CAUSAL;
import org.app.appgenesis.dao.Ordecost;
import org.app.appgenesis.dao.GMA_PKID;

import org.app.appgenesis.dao.PersonaDao;
import org.app.appgenesis.dao.OrdePersDao;
import org.app.appgenesis.dao.MaterialDao;
import org.app.appgenesis.dao.OrdeMateDao;
import org.app.appgenesis.dao.DibujoDao;
import org.app.appgenesis.dao.FirmaDao;
import org.app.appgenesis.dao.ComentarioDao;
import org.app.appgenesis.dao.FotografiaDao;
import org.app.appgenesis.dao.Gop_ordeatriDao;
import org.app.appgenesis.dao.GOP_ATRIBUTOSDao;
import org.app.appgenesis.dao.GOP_ORDEESTADao;
import org.app.appgenesis.dao.Gma_costtitrDao;
import org.app.appgenesis.dao.Gro_ordenDao;
import org.app.appgenesis.dao.UnidadMedidaDao;
import org.app.appgenesis.dao.GMA_CAUSALDao;
import org.app.appgenesis.dao.OrdecostDao;
import org.app.appgenesis.dao.GMA_PKIDDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personaDaoConfig;
    private final DaoConfig ordePersDaoConfig;
    private final DaoConfig materialDaoConfig;
    private final DaoConfig ordeMateDaoConfig;
    private final DaoConfig dibujoDaoConfig;
    private final DaoConfig firmaDaoConfig;
    private final DaoConfig comentarioDaoConfig;
    private final DaoConfig fotografiaDaoConfig;
    private final DaoConfig gop_ordeatriDaoConfig;
    private final DaoConfig gOP_ATRIBUTOSDaoConfig;
    private final DaoConfig gOP_ORDEESTADaoConfig;
    private final DaoConfig gma_costtitrDaoConfig;
    private final DaoConfig gro_ordenDaoConfig;
    private final DaoConfig unidadMedidaDaoConfig;
    private final DaoConfig gMA_CAUSALDaoConfig;
    private final DaoConfig ordecostDaoConfig;
    private final DaoConfig gMA_PKIDDaoConfig;

    private final PersonaDao personaDao;
    private final OrdePersDao ordePersDao;
    private final MaterialDao materialDao;
    private final OrdeMateDao ordeMateDao;
    private final DibujoDao dibujoDao;
    private final FirmaDao firmaDao;
    private final ComentarioDao comentarioDao;
    private final FotografiaDao fotografiaDao;
    private final Gop_ordeatriDao gop_ordeatriDao;
    private final GOP_ATRIBUTOSDao gOP_ATRIBUTOSDao;
    private final GOP_ORDEESTADao gOP_ORDEESTADao;
    private final Gma_costtitrDao gma_costtitrDao;
    private final Gro_ordenDao gro_ordenDao;
    private final UnidadMedidaDao unidadMedidaDao;
    private final GMA_CAUSALDao gMA_CAUSALDao;
    private final OrdecostDao ordecostDao;
    private final GMA_PKIDDao gMA_PKIDDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personaDaoConfig = daoConfigMap.get(PersonaDao.class).clone();
        personaDaoConfig.initIdentityScope(type);

        ordePersDaoConfig = daoConfigMap.get(OrdePersDao.class).clone();
        ordePersDaoConfig.initIdentityScope(type);

        materialDaoConfig = daoConfigMap.get(MaterialDao.class).clone();
        materialDaoConfig.initIdentityScope(type);

        ordeMateDaoConfig = daoConfigMap.get(OrdeMateDao.class).clone();
        ordeMateDaoConfig.initIdentityScope(type);

        dibujoDaoConfig = daoConfigMap.get(DibujoDao.class).clone();
        dibujoDaoConfig.initIdentityScope(type);

        firmaDaoConfig = daoConfigMap.get(FirmaDao.class).clone();
        firmaDaoConfig.initIdentityScope(type);

        comentarioDaoConfig = daoConfigMap.get(ComentarioDao.class).clone();
        comentarioDaoConfig.initIdentityScope(type);

        fotografiaDaoConfig = daoConfigMap.get(FotografiaDao.class).clone();
        fotografiaDaoConfig.initIdentityScope(type);

        gop_ordeatriDaoConfig = daoConfigMap.get(Gop_ordeatriDao.class).clone();
        gop_ordeatriDaoConfig.initIdentityScope(type);

        gOP_ATRIBUTOSDaoConfig = daoConfigMap.get(GOP_ATRIBUTOSDao.class).clone();
        gOP_ATRIBUTOSDaoConfig.initIdentityScope(type);

        gOP_ORDEESTADaoConfig = daoConfigMap.get(GOP_ORDEESTADao.class).clone();
        gOP_ORDEESTADaoConfig.initIdentityScope(type);

        gma_costtitrDaoConfig = daoConfigMap.get(Gma_costtitrDao.class).clone();
        gma_costtitrDaoConfig.initIdentityScope(type);

        gro_ordenDaoConfig = daoConfigMap.get(Gro_ordenDao.class).clone();
        gro_ordenDaoConfig.initIdentityScope(type);

        unidadMedidaDaoConfig = daoConfigMap.get(UnidadMedidaDao.class).clone();
        unidadMedidaDaoConfig.initIdentityScope(type);

        gMA_CAUSALDaoConfig = daoConfigMap.get(GMA_CAUSALDao.class).clone();
        gMA_CAUSALDaoConfig.initIdentityScope(type);

        ordecostDaoConfig = daoConfigMap.get(OrdecostDao.class).clone();
        ordecostDaoConfig.initIdentityScope(type);

        gMA_PKIDDaoConfig = daoConfigMap.get(GMA_PKIDDao.class).clone();
        gMA_PKIDDaoConfig.initIdentityScope(type);

        personaDao = new PersonaDao(personaDaoConfig, this);
        ordePersDao = new OrdePersDao(ordePersDaoConfig, this);
        materialDao = new MaterialDao(materialDaoConfig, this);
        ordeMateDao = new OrdeMateDao(ordeMateDaoConfig, this);
        dibujoDao = new DibujoDao(dibujoDaoConfig, this);
        firmaDao = new FirmaDao(firmaDaoConfig, this);
        comentarioDao = new ComentarioDao(comentarioDaoConfig, this);
        fotografiaDao = new FotografiaDao(fotografiaDaoConfig, this);
        gop_ordeatriDao = new Gop_ordeatriDao(gop_ordeatriDaoConfig, this);
        gOP_ATRIBUTOSDao = new GOP_ATRIBUTOSDao(gOP_ATRIBUTOSDaoConfig, this);
        gOP_ORDEESTADao = new GOP_ORDEESTADao(gOP_ORDEESTADaoConfig, this);
        gma_costtitrDao = new Gma_costtitrDao(gma_costtitrDaoConfig, this);
        gro_ordenDao = new Gro_ordenDao(gro_ordenDaoConfig, this);
        unidadMedidaDao = new UnidadMedidaDao(unidadMedidaDaoConfig, this);
        gMA_CAUSALDao = new GMA_CAUSALDao(gMA_CAUSALDaoConfig, this);
        ordecostDao = new OrdecostDao(ordecostDaoConfig, this);
        gMA_PKIDDao = new GMA_PKIDDao(gMA_PKIDDaoConfig, this);

        registerDao(Persona.class, personaDao);
        registerDao(OrdePers.class, ordePersDao);
        registerDao(Material.class, materialDao);
        registerDao(OrdeMate.class, ordeMateDao);
        registerDao(Dibujo.class, dibujoDao);
        registerDao(Firma.class, firmaDao);
        registerDao(Comentario.class, comentarioDao);
        registerDao(Fotografia.class, fotografiaDao);
        registerDao(Gop_ordeatri.class, gop_ordeatriDao);
        registerDao(GOP_ATRIBUTOS.class, gOP_ATRIBUTOSDao);
        registerDao(GOP_ORDEESTA.class, gOP_ORDEESTADao);
        registerDao(Gma_costtitr.class, gma_costtitrDao);
        registerDao(Gro_orden.class, gro_ordenDao);
        registerDao(UnidadMedida.class, unidadMedidaDao);
        registerDao(GMA_CAUSAL.class, gMA_CAUSALDao);
        registerDao(Ordecost.class, ordecostDao);
        registerDao(GMA_PKID.class, gMA_PKIDDao);
    }
    
    public void clear() {
        personaDaoConfig.getIdentityScope().clear();
        ordePersDaoConfig.getIdentityScope().clear();
        materialDaoConfig.getIdentityScope().clear();
        ordeMateDaoConfig.getIdentityScope().clear();
        dibujoDaoConfig.getIdentityScope().clear();
        firmaDaoConfig.getIdentityScope().clear();
        comentarioDaoConfig.getIdentityScope().clear();
        fotografiaDaoConfig.getIdentityScope().clear();
        gop_ordeatriDaoConfig.getIdentityScope().clear();
        gOP_ATRIBUTOSDaoConfig.getIdentityScope().clear();
        gOP_ORDEESTADaoConfig.getIdentityScope().clear();
        gma_costtitrDaoConfig.getIdentityScope().clear();
        gro_ordenDaoConfig.getIdentityScope().clear();
        unidadMedidaDaoConfig.getIdentityScope().clear();
        gMA_CAUSALDaoConfig.getIdentityScope().clear();
        ordecostDaoConfig.getIdentityScope().clear();
        gMA_PKIDDaoConfig.getIdentityScope().clear();
    }

    public PersonaDao getPersonaDao() {
        return personaDao;
    }

    public OrdePersDao getOrdePersDao() {
        return ordePersDao;
    }

    public MaterialDao getMaterialDao() {
        return materialDao;
    }

    public OrdeMateDao getOrdeMateDao() {
        return ordeMateDao;
    }

    public DibujoDao getDibujoDao() {
        return dibujoDao;
    }

    public FirmaDao getFirmaDao() {
        return firmaDao;
    }

    public ComentarioDao getComentarioDao() {
        return comentarioDao;
    }

    public FotografiaDao getFotografiaDao() {
        return fotografiaDao;
    }

    public Gop_ordeatriDao getGop_ordeatriDao() {
        return gop_ordeatriDao;
    }

    public GOP_ATRIBUTOSDao getGOP_ATRIBUTOSDao() {
        return gOP_ATRIBUTOSDao;
    }

    public GOP_ORDEESTADao getGOP_ORDEESTADao() {
        return gOP_ORDEESTADao;
    }

    public Gma_costtitrDao getGma_costtitrDao() {
        return gma_costtitrDao;
    }

    public Gro_ordenDao getGro_ordenDao() {
        return gro_ordenDao;
    }

    public UnidadMedidaDao getUnidadMedidaDao() {
        return unidadMedidaDao;
    }

    public GMA_CAUSALDao getGMA_CAUSALDao() {
        return gMA_CAUSALDao;
    }

    public OrdecostDao getOrdecostDao() {
        return ordecostDao;
    }

    public GMA_PKIDDao getGMA_PKIDDao() {
        return gMA_PKIDDao;
    }

}
