package org.app.appgenesis.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table DIBUJO.
 */
public class Dibujo {

    private Long id;
    private Float x;
    private Float y;
    private String accion;
    private Long idFirma;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Dibujo() {
    }

    public Dibujo(Long id) {
        this.id = id;
    }

    public Dibujo(Long id, Float x, Float y, String accion, Long idFirma) {
        this.id = id;
        this.x = x;
        this.y = y;
        this.accion = accion;
        this.idFirma = idFirma;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Float getX() {
        return x;
    }

    public void setX(Float x) {
        this.x = x;
    }

    public Float getY() {
        return y;
    }

    public void setY(Float y) {
        this.y = y;
    }

    public String getAccion() {
        return accion;
    }

    public void setAccion(String accion) {
        this.accion = accion;
    }

    public Long getIdFirma() {
        return idFirma;
    }

    public void setIdFirma(Long idFirma) {
        this.idFirma = idFirma;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
