package org.app.appgenesis.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table FIRMA.
 */
public class Firma {

    private Long id;
    private String documento;
    private String nombre;
    private String Correo;
    private String fecha;
    private String estado;
    private String usuario;
    private String foto;
    private Long idOrden;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Firma() {
    }

    public Firma(Long id) {
        this.id = id;
    }

    public Firma(Long id, String documento, String nombre, String Correo, String fecha, String estado, String usuario, String foto, Long idOrden) {
        this.id = id;
        this.documento = documento;
        this.nombre = nombre;
        this.Correo = Correo;
        this.fecha = fecha;
        this.estado = estado;
        this.usuario = usuario;
        this.foto = foto;
        this.idOrden = idOrden;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDocumento() {
        return documento;
    }

    public void setDocumento(String documento) {
        this.documento = documento;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getCorreo() {
        return Correo;
    }

    public void setCorreo(String Correo) {
        this.Correo = Correo;
    }

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getFoto() {
        return foto;
    }

    public void setFoto(String foto) {
        this.foto = foto;
    }

    public Long getIdOrden() {
        return idOrden;
    }

    public void setIdOrden(Long idOrden) {
        this.idOrden = idOrden;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
