package org.app.appgenesis.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table FOTOGRAFIA.
 */
public class Fotografia {

    private Long id;
    private Long Fecha;
    private String Descripcion;
    private String Foto;
    private Long IdOrden;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Fotografia() {
    }

    public Fotografia(Long id) {
        this.id = id;
    }

    public Fotografia(Long id, Long Fecha, String Descripcion, String Foto, Long IdOrden) {
        this.id = id;
        this.Fecha = Fecha;
        this.Descripcion = Descripcion;
        this.Foto = Foto;
        this.IdOrden = IdOrden;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getFecha() {
        return Fecha;
    }

    public void setFecha(Long Fecha) {
        this.Fecha = Fecha;
    }

    public String getDescripcion() {
        return Descripcion;
    }

    public void setDescripcion(String Descripcion) {
        this.Descripcion = Descripcion;
    }

    public String getFoto() {
        return Foto;
    }

    public void setFoto(String Foto) {
        this.Foto = Foto;
    }

    public Long getIdOrden() {
        return IdOrden;
    }

    public void setIdOrden(Long IdOrden) {
        this.IdOrden = IdOrden;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
