package org.app.appgenesis.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table GMA__CAUSAL.
 */
public class GMA_CAUSAL {

    private Long id;
    private String causcons;
    private String causdesc;
    private String caustipo;
    private String causesta;
    private String caususcr;
    private String causfecr;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GMA_CAUSAL() {
    }

    public GMA_CAUSAL(Long id) {
        this.id = id;
    }

    public GMA_CAUSAL(Long id, String causcons, String causdesc, String caustipo, String causesta, String caususcr, String causfecr) {
        this.id = id;
        this.causcons = causcons;
        this.causdesc = causdesc;
        this.caustipo = caustipo;
        this.causesta = causesta;
        this.caususcr = caususcr;
        this.causfecr = causfecr;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCauscons() {
        return causcons;
    }

    public void setCauscons(String causcons) {
        this.causcons = causcons;
    }

    public String getCausdesc() {
        return causdesc;
    }

    public void setCausdesc(String causdesc) {
        this.causdesc = causdesc;
    }

    public String getCaustipo() {
        return caustipo;
    }

    public void setCaustipo(String caustipo) {
        this.caustipo = caustipo;
    }

    public String getCausesta() {
        return causesta;
    }

    public void setCausesta(String causesta) {
        this.causesta = causesta;
    }

    public String getCaususcr() {
        return caususcr;
    }

    public void setCaususcr(String caususcr) {
        this.caususcr = caususcr;
    }

    public String getCausfecr() {
        return causfecr;
    }

    public void setCausfecr(String causfecr) {
        this.causfecr = causfecr;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
