package org.app.appgenesis.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table GMA_COSTTITR.
 */
public class Gma_costtitr {

    private Long id;
    private Long csttcons;
    private Long cstttitr;
    private String csttnomb;
    private String csttdesc;
    private String csttvalo;
    private String csttfein;
    private String csttfefi;
    private Long csttesta;
    private String csttuscr;
    private String csttfecr;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Gma_costtitr() {
    }

    public Gma_costtitr(Long id) {
        this.id = id;
    }

    public Gma_costtitr(Long id, Long csttcons, Long cstttitr, String csttnomb, String csttdesc, String csttvalo, String csttfein, String csttfefi, Long csttesta, String csttuscr, String csttfecr) {
        this.id = id;
        this.csttcons = csttcons;
        this.cstttitr = cstttitr;
        this.csttnomb = csttnomb;
        this.csttdesc = csttdesc;
        this.csttvalo = csttvalo;
        this.csttfein = csttfein;
        this.csttfefi = csttfefi;
        this.csttesta = csttesta;
        this.csttuscr = csttuscr;
        this.csttfecr = csttfecr;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCsttcons() {
        return csttcons;
    }

    public void setCsttcons(Long csttcons) {
        this.csttcons = csttcons;
    }

    public Long getCstttitr() {
        return cstttitr;
    }

    public void setCstttitr(Long cstttitr) {
        this.cstttitr = cstttitr;
    }

    public String getCsttnomb() {
        return csttnomb;
    }

    public void setCsttnomb(String csttnomb) {
        this.csttnomb = csttnomb;
    }

    public String getCsttdesc() {
        return csttdesc;
    }

    public void setCsttdesc(String csttdesc) {
        this.csttdesc = csttdesc;
    }

    public String getCsttvalo() {
        return csttvalo;
    }

    public void setCsttvalo(String csttvalo) {
        this.csttvalo = csttvalo;
    }

    public String getCsttfein() {
        return csttfein;
    }

    public void setCsttfein(String csttfein) {
        this.csttfein = csttfein;
    }

    public String getCsttfefi() {
        return csttfefi;
    }

    public void setCsttfefi(String csttfefi) {
        this.csttfefi = csttfefi;
    }

    public Long getCsttesta() {
        return csttesta;
    }

    public void setCsttesta(Long csttesta) {
        this.csttesta = csttesta;
    }

    public String getCsttuscr() {
        return csttuscr;
    }

    public void setCsttuscr(String csttuscr) {
        this.csttuscr = csttuscr;
    }

    public String getCsttfecr() {
        return csttfecr;
    }

    public void setCsttfecr(String csttfecr) {
        this.csttfecr = csttfecr;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
