package org.app.appgenesis.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table GOP__ORDEESTA.
 */
public class GOP_ORDEESTA {

    private Long id;
    private String ORESCONS;
    private String ORESORDE;
    private String ORESESTA;
    private String ORESOBSE;
    private String ORESUSCR;
    private String ORESFECR;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GOP_ORDEESTA() {
    }

    public GOP_ORDEESTA(Long id) {
        this.id = id;
    }

    public GOP_ORDEESTA(Long id, String ORESCONS, String ORESORDE, String ORESESTA, String ORESOBSE, String ORESUSCR, String ORESFECR) {
        this.id = id;
        this.ORESCONS = ORESCONS;
        this.ORESORDE = ORESORDE;
        this.ORESESTA = ORESESTA;
        this.ORESOBSE = ORESOBSE;
        this.ORESUSCR = ORESUSCR;
        this.ORESFECR = ORESFECR;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getORESCONS() {
        return ORESCONS;
    }

    public void setORESCONS(String ORESCONS) {
        this.ORESCONS = ORESCONS;
    }

    public String getORESORDE() {
        return ORESORDE;
    }

    public void setORESORDE(String ORESORDE) {
        this.ORESORDE = ORESORDE;
    }

    public String getORESESTA() {
        return ORESESTA;
    }

    public void setORESESTA(String ORESESTA) {
        this.ORESESTA = ORESESTA;
    }

    public String getORESOBSE() {
        return ORESOBSE;
    }

    public void setORESOBSE(String ORESOBSE) {
        this.ORESOBSE = ORESOBSE;
    }

    public String getORESUSCR() {
        return ORESUSCR;
    }

    public void setORESUSCR(String ORESUSCR) {
        this.ORESUSCR = ORESUSCR;
    }

    public String getORESFECR() {
        return ORESFECR;
    }

    public void setORESFECR(String ORESFECR) {
        this.ORESFECR = ORESFECR;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
