package org.app.appgenesis.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ORDE_MATE.
 */
public class OrdeMate {

    private Long id;
    private String cantidad;
    private Long idMaterial;
    private Long idOrden;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public OrdeMate() {
    }

    public OrdeMate(Long id) {
        this.id = id;
    }

    public OrdeMate(Long id, String cantidad, Long idMaterial, Long idOrden) {
        this.id = id;
        this.cantidad = cantidad;
        this.idMaterial = idMaterial;
        this.idOrden = idOrden;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCantidad() {
        return cantidad;
    }

    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }

    public Long getIdMaterial() {
        return idMaterial;
    }

    public void setIdMaterial(Long idMaterial) {
        this.idMaterial = idMaterial;
    }

    public Long getIdOrden() {
        return idOrden;
    }

    public void setIdOrden(Long idOrden) {
        this.idOrden = idOrden;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
