package org.app.appgenesis.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ORDECOST.
 */
public class Ordecost {

    private Long id;
    private String usua;
    private String sscr;
    private Boolean gene;
    private String valor;
    private String resp;
    private Long IdOrden;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Ordecost() {
    }

    public Ordecost(Long id) {
        this.id = id;
    }

    public Ordecost(Long id, String usua, String sscr, Boolean gene, String valor, String resp, Long IdOrden) {
        this.id = id;
        this.usua = usua;
        this.sscr = sscr;
        this.gene = gene;
        this.valor = valor;
        this.resp = resp;
        this.IdOrden = IdOrden;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsua() {
        return usua;
    }

    public void setUsua(String usua) {
        this.usua = usua;
    }

    public String getSscr() {
        return sscr;
    }

    public void setSscr(String sscr) {
        this.sscr = sscr;
    }

    public Boolean getGene() {
        return gene;
    }

    public void setGene(Boolean gene) {
        this.gene = gene;
    }

    public String getValor() {
        return valor;
    }

    public void setValor(String valor) {
        this.valor = valor;
    }

    public String getResp() {
        return resp;
    }

    public void setResp(String resp) {
        this.resp = resp;
    }

    public Long getIdOrden() {
        return IdOrden;
    }

    public void setIdOrden(Long IdOrden) {
        this.IdOrden = IdOrden;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
