package org.app.atenciondeturnos.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import org.app.atenciondeturnos.dao.GDB_TURNOSDao;
import org.app.atenciondeturnos.dao.GDB_TURNPERSDao;
import org.app.atenciondeturnos.dao.GDB_VALVULADao;
import org.app.atenciondeturnos.dao.TurnComeDao;
import org.app.atenciondeturnos.dao.TurnPersDao;
import org.app.atenciondeturnos.dao.TurnPersTurnDao;
import org.app.atenciondeturnos.dao.TurnMateDao;
import org.app.atenciondeturnos.dao.TurnFirmDao;
import org.app.atenciondeturnos.dao.TurnMateTurnDao;
import org.app.atenciondeturnos.dao.TurnUnidMediDao;
import org.app.atenciondeturnos.dao.GMA_PKIDTurnoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        GDB_TURNOSDao.createTable(db, ifNotExists);
        GDB_TURNPERSDao.createTable(db, ifNotExists);
        GDB_VALVULADao.createTable(db, ifNotExists);
        TurnComeDao.createTable(db, ifNotExists);
        TurnPersDao.createTable(db, ifNotExists);
        TurnPersTurnDao.createTable(db, ifNotExists);
        TurnMateDao.createTable(db, ifNotExists);
        TurnFirmDao.createTable(db, ifNotExists);
        TurnMateTurnDao.createTable(db, ifNotExists);
        TurnUnidMediDao.createTable(db, ifNotExists);
        GMA_PKIDTurnoDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        GDB_TURNOSDao.dropTable(db, ifExists);
        GDB_TURNPERSDao.dropTable(db, ifExists);
        GDB_VALVULADao.dropTable(db, ifExists);
        TurnComeDao.dropTable(db, ifExists);
        TurnPersDao.dropTable(db, ifExists);
        TurnPersTurnDao.dropTable(db, ifExists);
        TurnMateDao.dropTable(db, ifExists);
        TurnFirmDao.dropTable(db, ifExists);
        TurnMateTurnDao.dropTable(db, ifExists);
        TurnUnidMediDao.dropTable(db, ifExists);
        GMA_PKIDTurnoDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(GDB_TURNOSDao.class);
        registerDaoClass(GDB_TURNPERSDao.class);
        registerDaoClass(GDB_VALVULADao.class);
        registerDaoClass(TurnComeDao.class);
        registerDaoClass(TurnPersDao.class);
        registerDaoClass(TurnPersTurnDao.class);
        registerDaoClass(TurnMateDao.class);
        registerDaoClass(TurnFirmDao.class);
        registerDaoClass(TurnMateTurnDao.class);
        registerDaoClass(TurnUnidMediDao.class);
        registerDaoClass(GMA_PKIDTurnoDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
