package org.app.atenciondeturnos.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import org.app.atenciondeturnos.dao.GDB_TURNOS;
import org.app.atenciondeturnos.dao.GDB_TURNPERS;
import org.app.atenciondeturnos.dao.GDB_VALVULA;
import org.app.atenciondeturnos.dao.TurnCome;
import org.app.atenciondeturnos.dao.TurnPers;
import org.app.atenciondeturnos.dao.TurnPersTurn;
import org.app.atenciondeturnos.dao.TurnMate;
import org.app.atenciondeturnos.dao.TurnFirm;
import org.app.atenciondeturnos.dao.TurnMateTurn;
import org.app.atenciondeturnos.dao.TurnUnidMedi;
import org.app.atenciondeturnos.dao.GMA_PKIDTurno;

import org.app.atenciondeturnos.dao.GDB_TURNOSDao;
import org.app.atenciondeturnos.dao.GDB_TURNPERSDao;
import org.app.atenciondeturnos.dao.GDB_VALVULADao;
import org.app.atenciondeturnos.dao.TurnComeDao;
import org.app.atenciondeturnos.dao.TurnPersDao;
import org.app.atenciondeturnos.dao.TurnPersTurnDao;
import org.app.atenciondeturnos.dao.TurnMateDao;
import org.app.atenciondeturnos.dao.TurnFirmDao;
import org.app.atenciondeturnos.dao.TurnMateTurnDao;
import org.app.atenciondeturnos.dao.TurnUnidMediDao;
import org.app.atenciondeturnos.dao.GMA_PKIDTurnoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gDB_TURNOSDaoConfig;
    private final DaoConfig gDB_TURNPERSDaoConfig;
    private final DaoConfig gDB_VALVULADaoConfig;
    private final DaoConfig turnComeDaoConfig;
    private final DaoConfig turnPersDaoConfig;
    private final DaoConfig turnPersTurnDaoConfig;
    private final DaoConfig turnMateDaoConfig;
    private final DaoConfig turnFirmDaoConfig;
    private final DaoConfig turnMateTurnDaoConfig;
    private final DaoConfig turnUnidMediDaoConfig;
    private final DaoConfig gMA_PKIDTurnoDaoConfig;

    private final GDB_TURNOSDao gDB_TURNOSDao;
    private final GDB_TURNPERSDao gDB_TURNPERSDao;
    private final GDB_VALVULADao gDB_VALVULADao;
    private final TurnComeDao turnComeDao;
    private final TurnPersDao turnPersDao;
    private final TurnPersTurnDao turnPersTurnDao;
    private final TurnMateDao turnMateDao;
    private final TurnFirmDao turnFirmDao;
    private final TurnMateTurnDao turnMateTurnDao;
    private final TurnUnidMediDao turnUnidMediDao;
    private final GMA_PKIDTurnoDao gMA_PKIDTurnoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gDB_TURNOSDaoConfig = daoConfigMap.get(GDB_TURNOSDao.class).clone();
        gDB_TURNOSDaoConfig.initIdentityScope(type);

        gDB_TURNPERSDaoConfig = daoConfigMap.get(GDB_TURNPERSDao.class).clone();
        gDB_TURNPERSDaoConfig.initIdentityScope(type);

        gDB_VALVULADaoConfig = daoConfigMap.get(GDB_VALVULADao.class).clone();
        gDB_VALVULADaoConfig.initIdentityScope(type);

        turnComeDaoConfig = daoConfigMap.get(TurnComeDao.class).clone();
        turnComeDaoConfig.initIdentityScope(type);

        turnPersDaoConfig = daoConfigMap.get(TurnPersDao.class).clone();
        turnPersDaoConfig.initIdentityScope(type);

        turnPersTurnDaoConfig = daoConfigMap.get(TurnPersTurnDao.class).clone();
        turnPersTurnDaoConfig.initIdentityScope(type);

        turnMateDaoConfig = daoConfigMap.get(TurnMateDao.class).clone();
        turnMateDaoConfig.initIdentityScope(type);

        turnFirmDaoConfig = daoConfigMap.get(TurnFirmDao.class).clone();
        turnFirmDaoConfig.initIdentityScope(type);

        turnMateTurnDaoConfig = daoConfigMap.get(TurnMateTurnDao.class).clone();
        turnMateTurnDaoConfig.initIdentityScope(type);

        turnUnidMediDaoConfig = daoConfigMap.get(TurnUnidMediDao.class).clone();
        turnUnidMediDaoConfig.initIdentityScope(type);

        gMA_PKIDTurnoDaoConfig = daoConfigMap.get(GMA_PKIDTurnoDao.class).clone();
        gMA_PKIDTurnoDaoConfig.initIdentityScope(type);

        gDB_TURNOSDao = new GDB_TURNOSDao(gDB_TURNOSDaoConfig, this);
        gDB_TURNPERSDao = new GDB_TURNPERSDao(gDB_TURNPERSDaoConfig, this);
        gDB_VALVULADao = new GDB_VALVULADao(gDB_VALVULADaoConfig, this);
        turnComeDao = new TurnComeDao(turnComeDaoConfig, this);
        turnPersDao = new TurnPersDao(turnPersDaoConfig, this);
        turnPersTurnDao = new TurnPersTurnDao(turnPersTurnDaoConfig, this);
        turnMateDao = new TurnMateDao(turnMateDaoConfig, this);
        turnFirmDao = new TurnFirmDao(turnFirmDaoConfig, this);
        turnMateTurnDao = new TurnMateTurnDao(turnMateTurnDaoConfig, this);
        turnUnidMediDao = new TurnUnidMediDao(turnUnidMediDaoConfig, this);
        gMA_PKIDTurnoDao = new GMA_PKIDTurnoDao(gMA_PKIDTurnoDaoConfig, this);

        registerDao(GDB_TURNOS.class, gDB_TURNOSDao);
        registerDao(GDB_TURNPERS.class, gDB_TURNPERSDao);
        registerDao(GDB_VALVULA.class, gDB_VALVULADao);
        registerDao(TurnCome.class, turnComeDao);
        registerDao(TurnPers.class, turnPersDao);
        registerDao(TurnPersTurn.class, turnPersTurnDao);
        registerDao(TurnMate.class, turnMateDao);
        registerDao(TurnFirm.class, turnFirmDao);
        registerDao(TurnMateTurn.class, turnMateTurnDao);
        registerDao(TurnUnidMedi.class, turnUnidMediDao);
        registerDao(GMA_PKIDTurno.class, gMA_PKIDTurnoDao);
    }
    
    public void clear() {
        gDB_TURNOSDaoConfig.getIdentityScope().clear();
        gDB_TURNPERSDaoConfig.getIdentityScope().clear();
        gDB_VALVULADaoConfig.getIdentityScope().clear();
        turnComeDaoConfig.getIdentityScope().clear();
        turnPersDaoConfig.getIdentityScope().clear();
        turnPersTurnDaoConfig.getIdentityScope().clear();
        turnMateDaoConfig.getIdentityScope().clear();
        turnFirmDaoConfig.getIdentityScope().clear();
        turnMateTurnDaoConfig.getIdentityScope().clear();
        turnUnidMediDaoConfig.getIdentityScope().clear();
        gMA_PKIDTurnoDaoConfig.getIdentityScope().clear();
    }

    public GDB_TURNOSDao getGDB_TURNOSDao() {
        return gDB_TURNOSDao;
    }

    public GDB_TURNPERSDao getGDB_TURNPERSDao() {
        return gDB_TURNPERSDao;
    }

    public GDB_VALVULADao getGDB_VALVULADao() {
        return gDB_VALVULADao;
    }

    public TurnComeDao getTurnComeDao() {
        return turnComeDao;
    }

    public TurnPersDao getTurnPersDao() {
        return turnPersDao;
    }

    public TurnPersTurnDao getTurnPersTurnDao() {
        return turnPersTurnDao;
    }

    public TurnMateDao getTurnMateDao() {
        return turnMateDao;
    }

    public TurnFirmDao getTurnFirmDao() {
        return turnFirmDao;
    }

    public TurnMateTurnDao getTurnMateTurnDao() {
        return turnMateTurnDao;
    }

    public TurnUnidMediDao getTurnUnidMediDao() {
        return turnUnidMediDao;
    }

    public GMA_PKIDTurnoDao getGMA_PKIDTurnoDao() {
        return gMA_PKIDTurnoDao;
    }

}
