package org.app.atenciondeturnos.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table GDB__VALVULA.
 */
public class GDB_VALVULA {

    private Long id;
    private Long VALVCONS;
    private String VALVDESC;
    private String VALVDIRE;
    private String VALVDIAM;
    private String VALVCOOR;
    private String VALVESTA;
    private String VALVUSCR;
    private String VALVFECR;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GDB_VALVULA() {
    }

    public GDB_VALVULA(Long id) {
        this.id = id;
    }

    public GDB_VALVULA(Long id, Long VALVCONS, String VALVDESC, String VALVDIRE, String VALVDIAM, String VALVCOOR, String VALVESTA, String VALVUSCR, String VALVFECR) {
        this.id = id;
        this.VALVCONS = VALVCONS;
        this.VALVDESC = VALVDESC;
        this.VALVDIRE = VALVDIRE;
        this.VALVDIAM = VALVDIAM;
        this.VALVCOOR = VALVCOOR;
        this.VALVESTA = VALVESTA;
        this.VALVUSCR = VALVUSCR;
        this.VALVFECR = VALVFECR;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getVALVCONS() {
        return VALVCONS;
    }

    public void setVALVCONS(Long VALVCONS) {
        this.VALVCONS = VALVCONS;
    }

    public String getVALVDESC() {
        return VALVDESC;
    }

    public void setVALVDESC(String VALVDESC) {
        this.VALVDESC = VALVDESC;
    }

    public String getVALVDIRE() {
        return VALVDIRE;
    }

    public void setVALVDIRE(String VALVDIRE) {
        this.VALVDIRE = VALVDIRE;
    }

    public String getVALVDIAM() {
        return VALVDIAM;
    }

    public void setVALVDIAM(String VALVDIAM) {
        this.VALVDIAM = VALVDIAM;
    }

    public String getVALVCOOR() {
        return VALVCOOR;
    }

    public void setVALVCOOR(String VALVCOOR) {
        this.VALVCOOR = VALVCOOR;
    }

    public String getVALVESTA() {
        return VALVESTA;
    }

    public void setVALVESTA(String VALVESTA) {
        this.VALVESTA = VALVESTA;
    }

    public String getVALVUSCR() {
        return VALVUSCR;
    }

    public void setVALVUSCR(String VALVUSCR) {
        this.VALVUSCR = VALVUSCR;
    }

    public String getVALVFECR() {
        return VALVFECR;
    }

    public void setVALVFECR(String VALVFECR) {
        this.VALVFECR = VALVFECR;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
