package org.app.atenciondeturnos.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table GDB__TURNPERS.
 */
public class GDB_TURNPERS {

    private Long id;
    private Long TUPECONS;
    private Long TUPETURN;
    private String TUPEPERS;
    private String TUPEFEIN;
    private String TUPEFEFI;
    private String TUPEOBSE;
    private String TUPEINIC;
    private String TUPEFINA;
    private String TUPEESTA;
    private String TUPEUSCR;
    private String TUPEFECR;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GDB_TURNPERS() {
    }

    public GDB_TURNPERS(Long id) {
        this.id = id;
    }

    public GDB_TURNPERS(Long id, Long TUPECONS, Long TUPETURN, String TUPEPERS, String TUPEFEIN, String TUPEFEFI, String TUPEOBSE, String TUPEINIC, String TUPEFINA, String TUPEESTA, String TUPEUSCR, String TUPEFECR) {
        this.id = id;
        this.TUPECONS = TUPECONS;
        this.TUPETURN = TUPETURN;
        this.TUPEPERS = TUPEPERS;
        this.TUPEFEIN = TUPEFEIN;
        this.TUPEFEFI = TUPEFEFI;
        this.TUPEOBSE = TUPEOBSE;
        this.TUPEINIC = TUPEINIC;
        this.TUPEFINA = TUPEFINA;
        this.TUPEESTA = TUPEESTA;
        this.TUPEUSCR = TUPEUSCR;
        this.TUPEFECR = TUPEFECR;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTUPECONS() {
        return TUPECONS;
    }

    public void setTUPECONS(Long TUPECONS) {
        this.TUPECONS = TUPECONS;
    }

    public Long getTUPETURN() {
        return TUPETURN;
    }

    public void setTUPETURN(Long TUPETURN) {
        this.TUPETURN = TUPETURN;
    }

    public String getTUPEPERS() {
        return TUPEPERS;
    }

    public void setTUPEPERS(String TUPEPERS) {
        this.TUPEPERS = TUPEPERS;
    }

    public String getTUPEFEIN() {
        return TUPEFEIN;
    }

    public void setTUPEFEIN(String TUPEFEIN) {
        this.TUPEFEIN = TUPEFEIN;
    }

    public String getTUPEFEFI() {
        return TUPEFEFI;
    }

    public void setTUPEFEFI(String TUPEFEFI) {
        this.TUPEFEFI = TUPEFEFI;
    }

    public String getTUPEOBSE() {
        return TUPEOBSE;
    }

    public void setTUPEOBSE(String TUPEOBSE) {
        this.TUPEOBSE = TUPEOBSE;
    }

    public String getTUPEINIC() {
        return TUPEINIC;
    }

    public void setTUPEINIC(String TUPEINIC) {
        this.TUPEINIC = TUPEINIC;
    }

    public String getTUPEFINA() {
        return TUPEFINA;
    }

    public void setTUPEFINA(String TUPEFINA) {
        this.TUPEFINA = TUPEFINA;
    }

    public String getTUPEESTA() {
        return TUPEESTA;
    }

    public void setTUPEESTA(String TUPEESTA) {
        this.TUPEESTA = TUPEESTA;
    }

    public String getTUPEUSCR() {
        return TUPEUSCR;
    }

    public void setTUPEUSCR(String TUPEUSCR) {
        this.TUPEUSCR = TUPEUSCR;
    }

    public String getTUPEFECR() {
        return TUPEFECR;
    }

    public void setTUPEFECR(String TUPEFECR) {
        this.TUPEFECR = TUPEFECR;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
