package org.app.atenciondeturnos.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table GMA__PKIDTURNO.
 */
public class GMA_PKIDTurno {

    private Long id;
    private String Tabla;
    private Integer cantidad;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GMA_PKIDTurno() {
    }

    public GMA_PKIDTurno(Long id) {
        this.id = id;
    }

    public GMA_PKIDTurno(Long id, String Tabla, Integer cantidad) {
        this.id = id;
        this.Tabla = Tabla;
        this.cantidad = cantidad;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTabla() {
        return Tabla;
    }

    public void setTabla(String Tabla) {
        this.Tabla = Tabla;
    }

    public Integer getCantidad() {
        return cantidad;
    }

    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
