package org.app.atenciondeturnos.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import org.app.atenciondeturnos.dao.TurnPersTurn;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table TURN_PERS_TURN.
*/
public class TurnPersTurnDao extends AbstractDao<TurnPersTurn, Long> {

    public static final String TABLENAME = "TURN_PERS_TURN";

    /**
     * Properties of entity TurnPersTurn.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IdPersona = new Property(1, Long.class, "idPersona", false, "ID_PERSONA");
        public final static Property IdTurno = new Property(2, Long.class, "idTurno", false, "ID_TURNO");
    };

    private Query<TurnPersTurn> turnPers_TurnPersQuery;
    private Query<TurnPersTurn> gDB_TURNOS_TurnPersQuery;

    public TurnPersTurnDao(DaoConfig config) {
        super(config);
    }
    
    public TurnPersTurnDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'TURN_PERS_TURN' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ID_PERSONA' INTEGER," + // 1: idPersona
                "'ID_TURNO' INTEGER);"); // 2: idTurno
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TURN_PERS_TURN'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TurnPersTurn entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long idPersona = entity.getIdPersona();
        if (idPersona != null) {
            stmt.bindLong(2, idPersona);
        }
 
        Long idTurno = entity.getIdTurno();
        if (idTurno != null) {
            stmt.bindLong(3, idTurno);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TurnPersTurn readEntity(Cursor cursor, int offset) {
        TurnPersTurn entity = new TurnPersTurn( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // idPersona
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // idTurno
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TurnPersTurn entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdPersona(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setIdTurno(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TurnPersTurn entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TurnPersTurn entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "turnPers" to-many relationship of TurnPers. */
    public List<TurnPersTurn> _queryTurnPers_TurnPers(Long idPersona) {
        synchronized (this) {
            if (turnPers_TurnPersQuery == null) {
                QueryBuilder<TurnPersTurn> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdPersona.eq(null));
                turnPers_TurnPersQuery = queryBuilder.build();
            }
        }
        Query<TurnPersTurn> query = turnPers_TurnPersQuery.forCurrentThread();
        query.setParameter(0, idPersona);
        return query.list();
    }

    /** Internal query to resolve the "turnPers" to-many relationship of GDB_TURNOS. */
    public List<TurnPersTurn> _queryGDB_TURNOS_TurnPers(Long idTurno) {
        synchronized (this) {
            if (gDB_TURNOS_TurnPersQuery == null) {
                QueryBuilder<TurnPersTurn> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdTurno.eq(null));
                gDB_TURNOS_TurnPersQuery = queryBuilder.build();
            }
        }
        Query<TurnPersTurn> query = gDB_TURNOS_TurnPersQuery.forCurrentThread();
        query.setParameter(0, idTurno);
        return query.list();
    }

}
