package org.app.atenciondeturnos.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TURN_MATE_TURN.
 */
public class TurnMateTurn {

    private Long id;
    private Integer cantidad;
    private Long idMaterial;
    private Long idTurno;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TurnMateTurn() {
    }

    public TurnMateTurn(Long id) {
        this.id = id;
    }

    public TurnMateTurn(Long id, Integer cantidad, Long idMaterial, Long idTurno) {
        this.id = id;
        this.cantidad = cantidad;
        this.idMaterial = idMaterial;
        this.idTurno = idTurno;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCantidad() {
        return cantidad;
    }

    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }

    public Long getIdMaterial() {
        return idMaterial;
    }

    public void setIdMaterial(Long idMaterial) {
        this.idMaterial = idMaterial;
    }

    public Long getIdTurno() {
        return idTurno;
    }

    public void setIdTurno(Long idTurno) {
        this.idTurno = idTurno;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
