package org.app.atenciondeturnos.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TURN_FIRM.
 */
public class TurnFirm {

    private Long id;
    private String codigo;
    private String nombre;
    private String Correo;
    private String fecha;
    private String estado;
    private String usuario;
    private String foto;
    private Long idTurno;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TurnFirm() {
    }

    public TurnFirm(Long id) {
        this.id = id;
    }

    public TurnFirm(Long id, String codigo, String nombre, String Correo, String fecha, String estado, String usuario, String foto, Long idTurno) {
        this.id = id;
        this.codigo = codigo;
        this.nombre = nombre;
        this.Correo = Correo;
        this.fecha = fecha;
        this.estado = estado;
        this.usuario = usuario;
        this.foto = foto;
        this.idTurno = idTurno;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getCorreo() {
        return Correo;
    }

    public void setCorreo(String Correo) {
        this.Correo = Correo;
    }

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getFoto() {
        return foto;
    }

    public void setFoto(String foto) {
        this.foto = foto;
    }

    public Long getIdTurno() {
        return idTurno;
    }

    public void setIdTurno(Long idTurno) {
        this.idTurno = idTurno;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
