package org.app.atenciondeturnos.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TURN_UNID_MEDI.
 */
public class TurnUnidMedi {

    private Long id;
    private String consecutivo;
    private String valor;
    private String simbolo;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TurnUnidMedi() {
    }

    public TurnUnidMedi(Long id) {
        this.id = id;
    }

    public TurnUnidMedi(Long id, String consecutivo, String valor, String simbolo) {
        this.id = id;
        this.consecutivo = consecutivo;
        this.valor = valor;
        this.simbolo = simbolo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getConsecutivo() {
        return consecutivo;
    }

    public void setConsecutivo(String consecutivo) {
        this.consecutivo = consecutivo;
    }

    public String getValor() {
        return valor;
    }

    public void setValor(String valor) {
        this.valor = valor;
    }

    public String getSimbolo() {
        return simbolo;
    }

    public void setSimbolo(String simbolo) {
        this.simbolo = simbolo;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
